pipeline
{
    agent any 
    stages
    {
        stage('ContinuousDownload-loans')
        {
            steps
            {
               git 'https://github.com/intelliqittrainings/maven.git'
                   
            }
            
        }
        stage('ContinuousBuild-loans')
        {
            steps
            {
                
              sh 'mvn package'
                  
            }
            
        }
        
    
    }
            
        
        
    
}
