pipeline
{
    agent any 
    stages
    {
        stage('ContinuousDownload-master')
        {
            steps
            {
                script
                {
                 try
                   {
                    git 'https://github.com/intelliqittrainings/maven.git'
                   }
                catch(Exception e5)
                    {
                      mail bcc: '', body: 'failed', cc: '', from: '', replyTo: '', subject: 'failed', to: 'saikrishna'
                    }
                }
                
            }
            
        }
        stage('ContinuousBuild-master')
        {
            steps
            {
                script
                {
                  try 
                   {
                    sh 'mvn package'
                   }
                   catch(Exception e5)
                   {
                    
                   }
                }
            }
            
        }
        stage('ContinuousDeployment-master')
        {
            steps
            {
               sh 'scp /home/ubuntu/.jenkins/workspace/DeclarativePipeline1/webapp/target/webapp.war ubuntu@172.31.88.115:/var/lib/tomcat9/webapps/testapp.war'
            }
            
        }
        stage('ContinuousTesting-master')
        {
            steps
            {
               git 'https://github.com/intelliqittrainings/FunctionalTesting.git'
               sh 'java -jar /home/ubuntu/.jenkins/workspace/DeclarativePipeline/testing.jar'
            }
            
        }
        stage('Continuousdelivery-master')
        {
            steps
            {
                 sh 'scp /home/ubuntu/.jenkins/workspace/DeclarativePipeline1/webapp/target/webapp.war ubuntu@172.31.87.155:/var/lib/tomcat9/webapps/prodapp.war' 
            }
        }
    
    }
            
        
        
    
}
